my:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:prod}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

spring:
  profiles:
    active: prod
