spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/subway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
springdoc:
  swagger-ui.path: /docs
